#!/usr/bin/env bash
# Render the "MILO: THE CAT WHO WANTED SPACE" vertical short.
#
#   1080x1920 · 30 fps · 1650 frames (55.000s) · 30 keyframes
#
# Handles two sandbox constraints automatically:
#   * remotion.media (Chrome Headless Shell CDN) may be unreachable -> unpack
#     Chromium from the @sparticuz/chromium npm package instead.
#   * Google Fonts may be unreachable -> the composition vendors Anton from
#     public/cat-space/fonts/, and we use an entry point that registers only
#     this composition (src/index.tsx pulls in compositions that fetch fonts
#     at import time).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSER="$ROOT/remotion-composer"
OUT="${1:-$ROOT/output/cat-to-space/milo-space-55s.mp4}"

mkdir -p "$(dirname "$OUT")"

# --- score -----------------------------------------------------------------
if [ ! -f "$COMPOSER/public/cat-space/score.wav" ]; then
  echo "==> generating procedural score"
  (cd "$ROOT" && python3 scripts/make_cat_space_score.py)
fi

# --- font ------------------------------------------------------------------
# Anton is inlined into src/antonFont.ts as base64 so the render needs no
# network and no async FontFace gate (a delayRender() around the font load
# outlives the render loop and trips Remotion's timeout).
if [ ! -f "$COMPOSER/src/antonFont.ts" ]; then
  echo "==> vendoring Anton from npm"
  (cd "$COMPOSER" && npm i @fontsource/anton --no-audit --no-fund >/dev/null)
  (cd "$COMPOSER" && node -e "
    const fs=require('fs');
    const b=fs.readFileSync('node_modules/@fontsource/anton/files/anton-latin-400-normal.woff2').toString('base64');
    fs.writeFileSync('src/antonFont.ts',
      '// Generated by scripts/render_cat_space.sh — Anton, SIL OFL 1.1.\n' +
      'export const ANTON_WOFF2_BASE64 =\n  \"'+b+'\";\n');
  ")
fi

# --- browser ---------------------------------------------------------------
BROWSER_ARGS=()
if [ -x /tmp/chromium ]; then
  BROWSER_ARGS=(--browser-executable=/tmp/chromium)
  export LD_LIBRARY_PATH="/tmp/chlibs/lib:/tmp/chsw:${LD_LIBRARY_PATH:-}"
elif ! curl -s -o /dev/null -m 10 https://remotion.media >/dev/null 2>&1; then
  echo "==> remotion.media unreachable, unpacking Chromium from npm"
  WORK=/tmp/chrome
  mkdir -p "$WORK" && cd "$WORK"
  [ -f package.json ] || npm init -y >/dev/null
  npm i @sparticuz/chromium --no-audit --no-fund >/dev/null
  node -e "require('@sparticuz/chromium').default.executablePath().then(p=>console.log(p))" >/dev/null
  node -e "
    const zlib=require('zlib'),fs=require('fs');
    for (const f of ['al2023.tar.br','swiftshader.tar.br']) {
      fs.writeFileSync('/tmp/'+f.replace('.br',''),
        zlib.brotliDecompressSync(fs.readFileSync('node_modules/@sparticuz/chromium/bin/'+f)));
    }"
  mkdir -p /tmp/chlibs /tmp/chsw
  tar -xf /tmp/al2023.tar -C /tmp/chlibs
  tar -xf /tmp/swiftshader.tar -C /tmp/chsw
  export LD_LIBRARY_PATH="/tmp/chlibs/lib:/tmp/chsw:${LD_LIBRARY_PATH:-}"
  BROWSER_ARGS=(--browser-executable=/tmp/chromium)
fi

# --- render ----------------------------------------------------------------
cd "$COMPOSER"
[ -d node_modules ] || npm install --no-audit --no-fund

echo "==> rendering -> $OUT"
npx remotion render src/catSpaceIndex.tsx CatSpace "$OUT" \
  --gl=swangle \
  --concurrency="${CONCURRENCY:-2}" \
  --codec=h264 \
  --crf=20 \
  --enforce-audio-track \
  "${BROWSER_ARGS[@]}"

echo "==> done: $OUT"
